# enter 8 no's input from user and display it uniquely
a=set()
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)
n=int(input("Enter no:"))
a.add(n)

print(a)